{{- if .Values.rbac.enabled -}}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: jupyterlab-serviceaccount
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: jupyterlab-serviceaccount
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: jupyterlab-serviceaccount
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: jupyterlab-serviceaccount
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods/log"]
  verbs: ["get", "list"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["events"]
  verbs: ["get", "list"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: jupyterlab-serviceaccount
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: jupyterlab-serviceaccount
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: jupyterlab-serviceaccount
roleRef:
  kind: Role
  name: jupyterlab-serviceaccount
  apiGroup: rbac.authorization.k8s.io
{{- end -}}

